### ISSUE TITLE
lightning strike when activating the enchanting table

### ISSUE THREAD

**Issue by Sharaj00** [ITsMrToad/ToadLib-mod#5]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Forge

### Describe the bug

Minecraft 1.20.1 Forge 47.3.0
https://mclo.gs/HxZEMUt - with other mods
https://mclo.gs/ftH6Mtn - with only ToadLib installed

### Steps to reproduce

just try use enchanting table

### What version of the toadlib are you using?

1.1.4

**Comment by ITsMrToad** [comment]
Update toadlib to 1.1.5
